name: news_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.6
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  sentry_flutter: ^8.9.0
  win32: ^5.7.2
  percent_indicator: ^4.2.3
  flutter_svg: ^1.0.3
  dotted_line: ^3.2.3
  animate_do: ^3.3.4
  flutter_skeleton_ui: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
  
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 800
